In [1]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_addons as tfa
from tensorflow import keras

In [3]:
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [4]:
X, y = load_wine(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, shuffle=True, random_state=0)

train_df = pd.DataFrame(X_train, columns=load_wine().feature_names)
test_df = pd.DataFrame(X_test, columns=load_wine().feature_names)

In [5]:
train_df.head(15)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0     13.64        3.10  2.56               15.2      116.0           2.70   
1     12.60        2.46  2.20               18.5       94.0           1.62   
2     11.96        1.09  2.30               21.0      101.0           3.38   
3     12.25        3.88  2.20               18.5      112.0           1.38   
4     14.30        1.92  2.72               20.0      120.0           2.80   
5     12.88        2.99  2.40               20.0      104.0           1.30   
6     13.49        3.59  2.19               19.5       88.0           1.62   
7     13.56        1.71  2.31               16.2      117.0           3.15   
8     14.34        1.68  2.70               25.0       98.0           2.80   
9     13.71        1.86  2.36               16.6      101.0           2.61   
10    12.22        1.29  1.94               19.0       92.0           2.36   
11    13.27        4.28  2.26               20.0      120.0           1.59   
12    13.16        3.57  2.15               21.0      102.0           1.50   
13    13.86        1.51  2.67               25.0       86.0           2.95   
14    12.85        3.27  2.58               22.0      106.0           1.65   

    flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0         3.03                  0.17             1.66             5.10  0.96   
1         0.66                  0.63             0.94             7.10  0.73   
2         2.14                  0.13             1.65             3.21  0.99   
3         0.78                  0.29             1.14             8.21  0.65   
4         3.14                  0.33             1.97             6.20  1.07   
5         1.22                  0.24             0.83             5.40  0.74   
6         0.48                  0.58             0.88             5.70  0.81   
7         3.29                  0.34             2.34             6.13  0.95   
8         1.31                  0.53             2.70            13.00  0.57   
9         2.88                  0.27             1.69             3.80  1.11   
10        2.04                  0.39             2.08             2.70  0.86   
11        0.69                  0.43             1.35            10.20  0.59   
12        0.55                  0.43             1.30             4.00  0.60   
13        2.86                  0.21             1.87             3.38  1.36   
14        0.60                  0.60             0.96             5.58  0.87   

    od280/od315_of_diluted_wines  proline  
0                           3.36    845.0  
1                           1.58    695.0  
2                           3.13    886.0  
3                           2.00    855.0  
4                           2.65   1280.0  
5                           1.42    530.0  
6                           1.82    580.0  
7                           3.38    795.0  
8                           1.96    660.0  
9                           4.00   1035.0  
10                          3.02    312.0  
11                          1.56    835.0  
12                          1.68    830.0  
13                          3.16    410.0  
14                          2.11    570.0

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       133 non-null    float64
 1   malic_acid                    133 non-null    float64
 2   ash                           133 non-null    float64
 3   alcalinity_of_ash             133 non-null    float64
 4   magnesium                     133 non-null    float64
 5   total_phenols                 133 non-null    float64
 6   flavanoids                    133 non-null    float64
 7   nonflavanoid_phenols          133 non-null    float64
 8   proanthocyanins               133 non-null    float64
 9   color_intensity               133 non-null    float64
 10  hue                           133 non-null    float64
 11  od280/od315_of_diluted_wines  133 non-null    float64
 12  proline                       133 non-null    float64
dtypes: fl

In [7]:
train_df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  133.000000  133.000000  133.000000          133.00000  133.000000   
mean    12.999398    2.390977    2.365489           19.51203  100.458647   
std      0.803811    1.122554    0.271995            3.52532   14.484846   
min     11.030000    0.890000    1.360000           10.60000   70.000000   
25%     12.370000    1.610000    2.210000           17.10000   89.000000   
50%     13.050000    1.900000    2.360000           19.50000   98.000000   
75%     13.640000    3.240000    2.560000           21.50000  107.000000   
max     14.750000    5.650000    3.220000           30.00000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     133.000000  133.000000            133.000000       133.000000   
mean        2.261579    1.956917              0.363985         1.609474   
std         0.613286    0.984769              0.127873         0.601056   
min         1.100000    0.470000              0.130000         0.420000   
25%         1.700000    1.020000              0.270000         1.150000   
50%         2.200000    2.040000              0.340000         1.560000   
75%         2.740000    2.790000              0.450000         1.960000   
max         3.880000    3.740000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  
count       133.000000  133.000000                    133.000000   133.000000  
mean          5.113083    0.947338                      2.586015   749.812030  
std           2.405212    0.233392                      0.725185   303.322165  
min           1.280000    0.540000                      1.270000   312.000000  
25%           3.210000    0.770000                      1.860000   515.000000  
50%           4.600000    0.950000                      2.770000   675.000000  
75%           6.600000    1.110000                      3.170000   985.000000  
max          13.000000    1.710000                      4.000000  1547.000000

In [8]:
class NumberSelector(BaseEstimator, TransformerMixin):
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[[self.key]]

In [9]:
cont_transformers = []
cont_columns = ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins','color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


for col in cont_columns:
    transfomer =  Pipeline([
                ('selector', NumberSelector(key=col)),
                ('standard', StandardScaler())
            ])
    cont_transformers.append((col, transfomer))


feats = FeatureUnion(cont_transformers)

In [10]:
X_train = feats.fit_transform(train_df)
X_test = feats.transform(test_df)

In [11]:
model = keras.Sequential([
    keras.layers.Dense(128, activation='relu', input_shape=(13, )),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(10)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])


In [12]:
print(y_train[:5])

[0 2 1 2 0]


In [13]:
h = model.fit(X_train, y_train, epochs=20,verbose=1)

Epoch 1/20
5/5 [==============================] - 0s 747us/step - loss: 2.2015 - accuracy: 0.1955
Epoch 2/20
5/5 [==============================] - 0s 748us/step - loss: 1.8373 - accuracy: 0.6391
Epoch 3/20
5/5 [==============================] - 0s 748us/step - loss: 1.5033 - accuracy: 0.8722
Epoch 4/20
5/5 [==============================] - 0s 748us/step - loss: 1.1965 - accuracy: 0.9549
Epoch 5/20
5/5 [==============================] - 0s 498us/step - loss: 0.9181 - accuracy: 0.9774
Epoch 6/20
5/5 [==============================] - 0s 498us/step - loss: 0.6799 - accuracy: 0.9774
Epoch 7/20
5/5 [==============================] - 0s 498us/step - loss: 0.4907 - accuracy: 0.9774
Epoch 8/20
5/5 [==============================] - 0s 499us/step - loss: 0.3554 - accuracy: 0.9774
Epoch 9/20
5/5 [==============================] - 0s 747us/step - loss: 0.2613 - accuracy: 0.9774
Epoch 10/20
5/5 [==============================] - 0s 498us/step - loss: 0.1974 - accuracy: 0.9774
Epoch 11/20
5/5 [==

In [14]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)

2/2 - 0s - loss: 0.0304 - accuracy: 1.0000 - 62ms/epoch - 31ms/step


In [15]:
print('\nTest accuracy:', test_acc)


Test accuracy: 1.0


In [16]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [17]:
predictions = probability_model.predict(X_test[:5])

1/1 [==============================] - 0s 36ms/step


In [18]:
print(np.argmax(predictions, axis=1))
print(y_test[:5])

[0 2 1 0 1]
[0 2 1 0 1]
